name:Build and Publish image to Docker Hub
on: [workflow_dispatch]

  jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: build image
        run: docker build ./api/ -t nabeena/todo:lastest

      - name: push image to docker hub
        run:
          docker push nabeena/todo:latest